# Database Configuration - Generated by setup_database_sqlserver.py
import os

class Config:
    # Database Configuration
    SQLALCHEMY_DATABASE_URI = 'mssql+pyodbc://@AYUSH\SQLEXPRESS/lifestyle_analytics?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes&encrypt=yes&trustservercertificate=yes'
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    
    # Other configurations
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'lifestyle-analytics-secret-key-2024'
    
    # Email configuration (add your details)
    MAIL_SERVER = os.environ.get('MAIL_SERVER') or 'smtp.gmail.com'
    MAIL_PORT = int(os.environ.get('MAIL_PORT') or 587)
    MAIL_USE_TLS = os.environ.get('MAIL_USE_TLS', 'true').lower() in ['true', 'on', '1']
    MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
    MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')

# SQL Server Connection Details:
# Server: AYUSH\SQLEXPRESS
# Database: lifestyle_analytics
# Driver: ODBC Driver 17 for SQL Server
# Authentication: Windows
